-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-02-01 23:51:52 AEDT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE centre CASCADE CONSTRAINTS;

DROP TABLE class CASCADE CONSTRAINTS;

DROP TABLE class_staffing CASCADE CONSTRAINTS;

DROP TABLE class_type CASCADE CONSTRAINTS;

DROP TABLE facility CASCADE CONSTRAINTS;

DROP TABLE fitness_assessment CASCADE CONSTRAINTS;

DROP TABLE member CASCADE CONSTRAINTS;

DROP TABLE member_class_attendance CASCADE CONSTRAINTS;

DROP TABLE member_class_signup CASCADE CONSTRAINTS;

DROP TABLE staff CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE centre (
    centre_id                NUMBER(3) NOT NULL,
    centre_name              VARCHAR2(30) NOT NULL,
    centre_address_street    VARCHAR2(30) NOT NULL,
    centre_address_town      VARCHAR2(30) NOT NULL,
    centre_address_postcode  CHAR(4) NOT NULL,
    staff_id                 NUMBER(3) NOT NULL,
    centre_address_street_no VARCHAR2(4) NOT NULL
);

COMMENT ON COLUMN centre.centre_id IS
    'unique centre id number';

COMMENT ON COLUMN centre.centre_name IS
    'name of the centre';

COMMENT ON COLUMN centre.centre_address_street IS
    'street address of centre';

COMMENT ON COLUMN centre.centre_address_town IS
    'town location of centre';

COMMENT ON COLUMN centre.centre_address_postcode IS
    'postcode of the centre';

COMMENT ON COLUMN centre.staff_id IS
    'unique staff id number';

COMMENT ON COLUMN centre.centre_address_street_no IS
    'street number of the address';

CREATE UNIQUE INDEX centre__idx ON
    centre (
        staff_id
    ASC );

ALTER TABLE centre ADD CONSTRAINT centre_pk PRIMARY KEY ( centre_id );

CREATE TABLE class (
    centre_id         NUMBER(3) NOT NULL,
    class_no          NUMBER(3) NOT NULL,
    class_duration    NUMBER(3) NOT NULL,
    class_description VARCHAR2(50),
    class_datetime    CHAR(12) NOT NULL,
    class_no_sessions NUMBER(3) NOT NULL,
    staff_id          NUMBER(3) NOT NULL,
    class_type_id     NUMBER(3) NOT NULL,
    class_gender      CHAR(1) NOT NULL,
    facility_room_no  NUMBER(3) NOT NULL
);

ALTER TABLE class
    ADD CONSTRAINT chk_genderchar CHECK ( class_gender IN ( 'M', 'W' ) );

COMMENT ON COLUMN class.centre_id IS
    'unique centre id number';

COMMENT ON COLUMN class.class_no IS
    'class number identifying class within a centre';

COMMENT ON COLUMN class.class_duration IS
    'duration of the class in minutes';

COMMENT ON COLUMN class.class_description IS
    'description of the class';

COMMENT ON COLUMN class.class_datetime IS
    'class time and date in the format HHMMDDMMYYYY';

COMMENT ON COLUMN class.class_no_sessions IS
    'total number of sessions of the class';

COMMENT ON COLUMN class.staff_id IS
    'unique staff id number';

COMMENT ON COLUMN class.class_type_id IS
    'identification number for class type';

COMMENT ON COLUMN class.class_gender IS
    'gender allowed in classes (M = mixed, W = women)';

COMMENT ON COLUMN class.facility_room_no IS
    'facility room number';

ALTER TABLE class ADD CONSTRAINT class_pk PRIMARY KEY ( class_no,
                                                        centre_id );

CREATE TABLE class_staffing (
    cs_id     NUMBER(3) NOT NULL,
    class_no  NUMBER(3) NOT NULL,
    staff_id  NUMBER(3) NOT NULL,
    centre_id NUMBER(3) NOT NULL
);

COMMENT ON COLUMN class_staffing.cs_id IS
    'Customer staffing ID';

COMMENT ON COLUMN class_staffing.class_no IS
    'class number identifying class within a centre';

COMMENT ON COLUMN class_staffing.staff_id IS
    'unique staff id number';

COMMENT ON COLUMN class_staffing.centre_id IS
    'unique centre id number';

ALTER TABLE class_staffing ADD CONSTRAINT class_staffing_pk PRIMARY KEY ( cs_id );

ALTER TABLE class_staffing
    ADD CONSTRAINT key_2 UNIQUE ( class_no,
                                  staff_id,
                                  centre_id );

CREATE TABLE class_type (
    class_type_id   NUMBER(3) NOT NULL,
    class_type_name VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN class_type.class_type_id IS
    'identification number for class type';

COMMENT ON COLUMN class_type.class_type_name IS
    'name of the class type';

ALTER TABLE class_type ADD CONSTRAINT class_type_pk PRIMARY KEY ( class_type_id );

CREATE TABLE facility (
    facility_room_no     NUMBER(3) NOT NULL,
    facility_description VARCHAR2(50),
    facility_name        VARCHAR2(30) NOT NULL,
    facility_cap         NUMBER(3) NOT NULL,
    centre_id            NUMBER(3) NOT NULL
);

COMMENT ON COLUMN facility.facility_room_no IS
    'facility room number';

COMMENT ON COLUMN facility.facility_description IS
    'description of the facility';

COMMENT ON COLUMN facility.facility_name IS
    'name of the facility';

COMMENT ON COLUMN facility.facility_cap IS
    'capacity of the facility';

COMMENT ON COLUMN facility.centre_id IS
    'unique centre id number';

ALTER TABLE facility ADD CONSTRAINT facility_pk PRIMARY KEY ( facility_room_no,
                                                              centre_id );

CREATE TABLE fitness_assessment (
    ass_date          CHAR(8) NOT NULL,
    ass_weight        NUMBER(3) NOT NULL,
    ass_bmi           NUMBER(3) NOT NULL,
    ass_vo2max        NUMBER(3) NOT NULL,
    ass_bloodpressure VARCHAR2(7) NOT NULL,
    member_no         NUMBER(3) NOT NULL,
    staff_id          NUMBER(3) NOT NULL
);

COMMENT ON COLUMN fitness_assessment.ass_date IS
    'assessment date in the format DDMMYYYY';

COMMENT ON COLUMN fitness_assessment.ass_weight IS
    'weight of member in assessment';

COMMENT ON COLUMN fitness_assessment.ass_bmi IS
    'BMI of the member in %';

COMMENT ON COLUMN fitness_assessment.ass_vo2max IS
    'VO2MAX of member';

COMMENT ON COLUMN fitness_assessment.ass_bloodpressure IS
    'recorded bloodpressure of member';

COMMENT ON COLUMN fitness_assessment.member_no IS
    'member number';

COMMENT ON COLUMN fitness_assessment.staff_id IS
    'unique staff id number';

ALTER TABLE fitness_assessment ADD CONSTRAINT fitness_assessment_pk PRIMARY KEY ( ass_date,
                                                                                  member_no );

CREATE TABLE member (
    member_no                NUMBER(3) NOT NULL,
    member_lname             VARCHAR2(30) NOT NULL,
    member_address_street    VARCHAR2(30) NOT NULL,
    member_mobile_no         VARCHAR2(10) NOT NULL,
    member_start_date        CHAR(8) NOT NULL,
    member_no_refer          NUMBER(3) NOT NULL,
    member_address_postcode  VARCHAR2(4) NOT NULL,
    member_address_town      VARCHAR2(20) NOT NULL,
    member_fname             VARCHAR2(20) NOT NULL,
    member_address_street_no VARCHAR2(4) NOT NULL
);

COMMENT ON COLUMN member.member_no IS
    'member number';

COMMENT ON COLUMN member.member_lname IS
    'last name of the member';

COMMENT ON COLUMN member.member_address_street IS
    'home address street of member';

COMMENT ON COLUMN member.member_mobile_no IS
    'mobile number of member';

COMMENT ON COLUMN member.member_start_date IS
    'commencement of membership in format DDMMYYYY';

COMMENT ON COLUMN member.member_no_refer IS
    'member number';

COMMENT ON COLUMN member.member_address_postcode IS
    'home address postcode of member';

COMMENT ON COLUMN member.member_address_town IS
    'home address town of member';

COMMENT ON COLUMN member.member_fname IS
    'member first name';

COMMENT ON COLUMN member.member_address_street_no IS
    'home address street number of member';

ALTER TABLE member ADD CONSTRAINT member_pk PRIMARY KEY ( member_no );

CREATE TABLE member_class_attendance (
    mem_cls_sign_id           NUMBER(3) NOT NULL,
    mem_class_attend_isattend CHAR(1) NOT NULL,
    mem_class_attend_date     CHAR(8) NOT NULL
);

ALTER TABLE member_class_attendance
    ADD CHECK ( mem_class_attend_isattend IN ( 'N', 'Y' ) );

COMMENT ON COLUMN member_class_attendance.mem_cls_sign_id IS
    'Member class signup ID';

COMMENT ON COLUMN member_class_attendance.mem_class_attend_isattend IS
    'whether the member attended the class occurence (Y/N)';

COMMENT ON COLUMN member_class_attendance.mem_class_attend_date IS
    'date of the class session in format DDMMYYYY';

ALTER TABLE member_class_attendance ADD CONSTRAINT member_class_attendance_pk PRIMARY KEY ( mem_cls_sign_id );

CREATE TABLE member_class_signup (
    mem_cls_sign_id        NUMBER(3) NOT NULL,
    mem_cls_sign_paydate   CHAR(8) NOT NULL,
    mem_cls_sign_ttlattend NUMBER(3) NOT NULL,
    member_no              NUMBER(3) NOT NULL,
    class_no               NUMBER(3) NOT NULL,
    centre_id              NUMBER(3) NOT NULL
);

COMMENT ON COLUMN member_class_signup.mem_cls_sign_id IS
    'Member class signup ID';

COMMENT ON COLUMN member_class_signup.mem_cls_sign_paydate IS
    'payment date in format DDMMYYYY';

COMMENT ON COLUMN member_class_signup.mem_cls_sign_ttlattend IS
    'total number of times member attended the classes scheduled';

COMMENT ON COLUMN member_class_signup.member_no IS
    'member number';

COMMENT ON COLUMN member_class_signup.class_no IS
    'class number identifying class within a centre';

COMMENT ON COLUMN member_class_signup.centre_id IS
    'unique centre id number';

ALTER TABLE member_class_signup ADD CONSTRAINT member_class_signup_pk PRIMARY KEY ( mem_cls_sign_id );

ALTER TABLE member_class_signup
    ADD CONSTRAINT key_2v2 UNIQUE ( class_no,
                                    centre_id,
                                    member_no );

CREATE TABLE staff (
    staff_id         NUMBER(3) NOT NULL,
    staff_first_name VARCHAR2(30) NOT NULL,
    staff_isfirstaid CHAR(1) NOT NULL,
    staff_role       CHAR(1) NOT NULL,
    staff_last_name  VARCHAR2(30) NOT NULL,
    staff_mobile_no  VARCHAR2(10) NOT NULL,
    staff_start_date CHAR(8) NOT NULL,
    centre_id        NUMBER(3) NOT NULL
);

ALTER TABLE staff
    ADD CONSTRAINT chk_yorn CHECK ( staff_isfirstaid IN ( 'N', 'Y' ) );

ALTER TABLE staff
    ADD CONSTRAINT chk_role CHECK ( staff_role IN ( 'A', 'C', 'D', 'M', 'P',
                                                    'S', 'T' ) );

COMMENT ON COLUMN staff.staff_id IS
    'unique staff id number';

COMMENT ON COLUMN staff.staff_first_name IS
    'first name of the staff member';

COMMENT ON COLUMN staff.staff_isfirstaid IS
    'is staff first aid trained (Y/N)';

COMMENT ON COLUMN staff.staff_role IS
    'Administration (A)
Cleaner (C)
Instructor Dry (D)
Instructor Pool (P)
Manager (only one per centre) (M)
Sales (S)
Security (T)';

COMMENT ON COLUMN staff.staff_last_name IS
    'staff last name';

COMMENT ON COLUMN staff.staff_mobile_no IS
    'staff mobile number';

COMMENT ON COLUMN staff.staff_start_date IS
    'staff start date in format DDMMYYYY';

COMMENT ON COLUMN staff.centre_id IS
    'unique centre id number';

ALTER TABLE staff ADD CONSTRAINT staff_pk PRIMARY KEY ( staff_id );

ALTER TABLE facility
    ADD CONSTRAINT centre_facility FOREIGN KEY ( centre_id )
        REFERENCES centre ( centre_id );

ALTER TABLE staff
    ADD CONSTRAINT centre_staff FOREIGN KEY ( centre_id )
        REFERENCES centre ( centre_id );

ALTER TABLE class_staffing
    ADD CONSTRAINT class_class_staffing FOREIGN KEY ( class_no,
                                                      centre_id )
        REFERENCES class ( class_no,
                           centre_id );

ALTER TABLE member_class_signup
    ADD CONSTRAINT class_mem_class_signup FOREIGN KEY ( class_no,
                                                        centre_id )
        REFERENCES class ( class_no,
                           centre_id );

ALTER TABLE class
    ADD CONSTRAINT class_type_class FOREIGN KEY ( class_type_id )
        REFERENCES class_type ( class_type_id );

ALTER TABLE class
    ADD CONSTRAINT "FACILITY>CLASS_has" FOREIGN KEY ( facility_room_no,
                                                      centre_id )
        REFERENCES facility ( facility_room_no,
                              centre_id );

ALTER TABLE member_class_attendance
    ADD CONSTRAINT mem_cl_signup_mem_cl_attend FOREIGN KEY ( mem_cls_sign_id )
        REFERENCES member_class_signup ( mem_cls_sign_id );

ALTER TABLE member_class_signup
    ADD CONSTRAINT mem_mem_class_signup FOREIGN KEY ( member_no )
        REFERENCES member ( member_no );

ALTER TABLE fitness_assessment
    ADD CONSTRAINT member_fit_assess FOREIGN KEY ( member_no )
        REFERENCES member ( member_no );

ALTER TABLE member
    ADD CONSTRAINT member_member FOREIGN KEY ( member_no_refer )
        REFERENCES member ( member_no );

ALTER TABLE centre
    ADD CONSTRAINT staff_centre FOREIGN KEY ( staff_id )
        REFERENCES staff ( staff_id );

ALTER TABLE class
    ADD CONSTRAINT staff_class FOREIGN KEY ( staff_id )
        REFERENCES staff ( staff_id );

ALTER TABLE class_staffing
    ADD CONSTRAINT staff_class_staffing FOREIGN KEY ( staff_id )
        REFERENCES staff ( staff_id );

ALTER TABLE fitness_assessment
    ADD CONSTRAINT staff_fit_assess FOREIGN KEY ( staff_id )
        REFERENCES staff ( staff_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             1
-- ALTER TABLE                             30
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
